[build]
  command = "npm run build"
  publish = "."

[functions]
  directory = "netlify/functions"

[dev]
  port = 8888

[[redirects]]
  from = "/ai-tools/projects/face-recognition/"
  to = "/ai-tools/projects/face-recognition/build/index.html"
  status = 200
  force = true

